language: objective-c
osx_image: xcode10.1
before_install:
  - carthage bootstrap --no-use-binaries --platform ios
script: xcodebuild clean build test -scheme 'RxPhotos iOS' -destination "platform=iOS Simulator,name=iPhone 8" -enableCodeCoverage YES
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'RxPhotos'
